server:
  port: 3000
  host: 0.0.0.0

kubernetes:
  inCluster: true
  #kubeconfig: c:/Users/NewtyCoffee/.kube/config # Optional, uses in-cluster config if not specified
  # namespace: default               # Optional, watches all namespaces if not specified
  serviceDiscoveryInterval: 60000    # milliseconds

actuator:
  defaultPort: 8080
  basePath: /actuator
  endpoints:
    health: /health
    info: /info
    metrics: /metrics
    logfile: /logfile
  # Annotations to look for in pods/services to find management port and context path
  managementPortAnnotation: spring-boot/management-port
  managementContextPathAnnotation: spring-boot/management-context-path

metrics:
  collectionInterval: 30000         # milliseconds
  retention:
    days: 7
    maxEntries: 1000

logging:
  level: info                        # debug, info, warn, error
  
logs:
  recentLimit: 10                    # Number of logs to show in the recent logs section
  websocketEnabled: true             # Enable real-time log monitoring via WebSocket
  refreshInterval: 5000              # Refresh interval for log polling when WebSocket is disabled