apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-springboot-dashboard-config
  labels:
    app: k8s-springboot-dashboard
data:
  config.yaml: |
    server:
      port: 3000
      host: 0.0.0.0

    kubernetes:
      inCluster: true
      # namespace: default  # Optional, watches all namespaces if not specified
      serviceDiscoveryInterval: 60000    # milliseconds

    actuator:
      defaultPort: 8080
      basePath: /management
      endpoints:
        health: /health
        info: /info
        metrics: /metrics
        logfile: /logfile
      managementPortAnnotation: spring-boot/management-port
      managementContextPathAnnotation: spring-boot/management-context-path

    metrics:
      collectionInterval: 30000         # milliseconds
      retention:
        days: 7
        maxEntries: 1000

    logging:
      level: info                        # debug, info, warn, error
