apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      serviceAccountName: k8s-springboot-dashboard-sa 
      containers:
        - name: dashboard
          image: k8s-springboot-dashboard
          args: ["node", "--enable-source-maps", "--inspect-brk=0.0.0.0:9229", "dist/server.js"]
          ports:
            - containerPort: 3000
            - containerPort: 9229
          env:
            - name: NODE_ENV
              value: development
