apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-dashboard
  labels:
    app: k8s-springboot-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-springboot-dashboard
  template:
    metadata:
      labels:
        app: k8s-springboot-dashboard
    spec:
      serviceAccountName: k8s-springboot-dashboard-sa
      containers:
      - name: dashboard
        image: k8s-springboot-dashboard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9229
          name: debug
        env:
        - name: NODE_ENV
          value: "production"
        - name: CONFIG_MAP_PATH
          value: "/app/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/services
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/services
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: k8s-springboot-dashboard-config
