# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-springboot-dashboard-sa
  namespace: default
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-springboot-dashboard-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-springboot-dashboard-binding
subjects:
  - kind: ServiceAccount
    name: k8s-springboot-dashboard-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-springboot-dashboard-role
  apiGroup: rbac.authorization.k8s.io
---
