# Server configuration
server:
  http2:
    enabled: true
  port: 5000
  servlet:
    context-path: /

# Spring configuration
spring:
  application:
    name: obserra-backend

  # Database configuration is disabled - using in-memory storage instead
  # datasource:
  #   url: jdbc:h2:mem:obserra
  #   username: sa
  #   password: 
  #   driver-class-name: org.h2.Driver

  # JPA configuration is disabled - using in-memory storage instead
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.H2Dialect
  #   show-sql: false

  # H2 Console configuration is disabled - using in-memory storage instead
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    root: INFO
    org.newtco.obserra: INFO
    org.newtco.obserra.backend.collector.CircuitBreaker: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.netflix.graphql.dgs: DEBUG
    org.newtco.obserra.backend.graphql: DEBUG


# Application-specific configuration
obserra:
  collectors:
    interval: 5s
    timeout: 30s

    max-concurrent-requests: 30

    spring-boot:
      enabled: true
      timeout: 5s
      check-interval: 5s
      health:
        check-interval: 1s
        show-components: true


    kubernetes:
      enabled: false

  # Service discovery configuration
  service-discovery:
    interval: 6s
    timeout: 5s
    kubernetes:
      enabled: false
