semi: true
singleQuote: false
tabWidth: 2
trailingComma: all
printWidth: 100
bracketSpacing: true
arrowParens: always
endOfLine: auto
jsxBracketSameLine: false
jsxSingleQuote: false
proseWrap: "always"
quoteProps: "as-needed"